// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4PXgxH2TA5jgeNSts87vZpdMCj5lkAz8',
    appId: '1:889302276831:web:dec94d6b35df901fcee76a',
    messagingSenderId: '889302276831',
    projectId: 'event-recorder-db',
    authDomain: 'event-recorder-db.firebaseapp.com',
    storageBucket: 'event-recorder-db.appspot.com',
    measurementId: 'G-7JHKRX9642',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8URv45OOvdepNNzy1gl4z88RT8fPqSUs',
    appId: '1:889302276831:android:8f32d8b664010a41cee76a',
    messagingSenderId: '889302276831',
    projectId: 'event-recorder-db',
    storageBucket: 'event-recorder-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6q3xdijX7OEyZ6IWIZD0TxfPiaPm1qXU',
    appId: '1:889302276831:ios:ab725d63a3fc1550cee76a',
    messagingSenderId: '889302276831',
    projectId: 'event-recorder-db',
    storageBucket: 'event-recorder-db.appspot.com',
    iosClientId: '889302276831-vr5d00u0vdff7vmo20gbc7lmt6rklenu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventRecorder',
  );
}
